/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: clientmessage.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./loginrequest";
import * as dependency_2 from "./loginresponse";
import * as dependency_3 from "./LoginByToken";
import * as dependency_4 from "./DealingDataInterval";
import * as dependency_5 from "./FetchDealingDataInterval";
import * as dependency_6 from "./FetchLoginDevice";
import * as dependency_7 from "./LoginDeviceLog";
import * as dependency_8 from "./SubscribeTicker";
import * as dependency_9 from "./TickData";
import * as pb_1 from "google-protobuf";
export namespace Oreka {
    export class ClientMessage extends pb_1.Message {
        #one_of_decls: number[][] = [[2], [3], [7], [10], [20], [87], [88], [46], [61]];
        constructor(data?: any[] | ({
            type?: string;
        } & (({
            loginrequest?: dependency_1.Oreka.LoginRequest;
        }) | ({
            loginresponse?: dependency_2.Oreka.LoginResponse;
        }) | ({
            fetchDealingdatainterval?: dependency_5.Oreka.FetchDealingDataInterval;
        }) | ({
            loginbytoken?: dependency_3.Oreka.LoginByToken;
        }) | ({
            dealingdatainterval?: dependency_4.Oreka.DealingDataInterval;
        }) | ({
            fetchlogindevice?: dependency_6.Oreka.FetchLoginDevice;
        }) | ({
            logindevicelog?: dependency_7.Oreka.LoginDeviceLog;
        }) | ({
            subscribeticker?: dependency_8.Oreka.SubscribeTicker;
        }) | ({
            tickdata?: dependency_9.Oreka.TickData;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("loginrequest" in data && data.loginrequest != undefined) {
                    this.loginrequest = data.loginrequest;
                }
                if ("loginresponse" in data && data.loginresponse != undefined) {
                    this.loginresponse = data.loginresponse;
                }
                if ("fetchDealingdatainterval" in data && data.fetchDealingdatainterval != undefined) {
                    this.fetchDealingdatainterval = data.fetchDealingdatainterval;
                }
                if ("loginbytoken" in data && data.loginbytoken != undefined) {
                    this.loginbytoken = data.loginbytoken;
                }
                if ("dealingdatainterval" in data && data.dealingdatainterval != undefined) {
                    this.dealingdatainterval = data.dealingdatainterval;
                }
                if ("fetchlogindevice" in data && data.fetchlogindevice != undefined) {
                    this.fetchlogindevice = data.fetchlogindevice;
                }
                if ("logindevicelog" in data && data.logindevicelog != undefined) {
                    this.logindevicelog = data.logindevicelog;
                }
                if ("subscribeticker" in data && data.subscribeticker != undefined) {
                    this.subscribeticker = data.subscribeticker;
                }
                if ("tickdata" in data && data.tickdata != undefined) {
                    this.tickdata = data.tickdata;
                }
            }
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get loginrequest() {
            return pb_1.Message.getWrapperField(this, dependency_1.Oreka.LoginRequest, 2) as dependency_1.Oreka.LoginRequest;
        }
        set loginrequest(value: dependency_1.Oreka.LoginRequest) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_loginrequest() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get loginresponse() {
            return pb_1.Message.getWrapperField(this, dependency_2.Oreka.LoginResponse, 3) as dependency_2.Oreka.LoginResponse;
        }
        set loginresponse(value: dependency_2.Oreka.LoginResponse) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[1], value);
        }
        get has_loginresponse() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get fetchDealingdatainterval() {
            return pb_1.Message.getWrapperField(this, dependency_5.Oreka.FetchDealingDataInterval, 7) as dependency_5.Oreka.FetchDealingDataInterval;
        }
        set fetchDealingdatainterval(value: dependency_5.Oreka.FetchDealingDataInterval) {
            pb_1.Message.setOneofWrapperField(this, 7, this.#one_of_decls[2], value);
        }
        get has_fetchDealingdatainterval() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get loginbytoken() {
            return pb_1.Message.getWrapperField(this, dependency_3.Oreka.LoginByToken, 10) as dependency_3.Oreka.LoginByToken;
        }
        set loginbytoken(value: dependency_3.Oreka.LoginByToken) {
            pb_1.Message.setOneofWrapperField(this, 10, this.#one_of_decls[3], value);
        }
        get has_loginbytoken() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get dealingdatainterval() {
            return pb_1.Message.getWrapperField(this, dependency_4.Oreka.DealingDataInterval, 20) as dependency_4.Oreka.DealingDataInterval;
        }
        set dealingdatainterval(value: dependency_4.Oreka.DealingDataInterval) {
            pb_1.Message.setOneofWrapperField(this, 20, this.#one_of_decls[4], value);
        }
        get has_dealingdatainterval() {
            return pb_1.Message.getField(this, 20) != null;
        }
        get fetchlogindevice() {
            return pb_1.Message.getWrapperField(this, dependency_6.Oreka.FetchLoginDevice, 87) as dependency_6.Oreka.FetchLoginDevice;
        }
        set fetchlogindevice(value: dependency_6.Oreka.FetchLoginDevice) {
            pb_1.Message.setOneofWrapperField(this, 87, this.#one_of_decls[5], value);
        }
        get has_fetchlogindevice() {
            return pb_1.Message.getField(this, 87) != null;
        }
        get logindevicelog() {
            return pb_1.Message.getWrapperField(this, dependency_7.Oreka.LoginDeviceLog, 88) as dependency_7.Oreka.LoginDeviceLog;
        }
        set logindevicelog(value: dependency_7.Oreka.LoginDeviceLog) {
            pb_1.Message.setOneofWrapperField(this, 88, this.#one_of_decls[6], value);
        }
        get has_logindevicelog() {
            return pb_1.Message.getField(this, 88) != null;
        }
        get subscribeticker() {
            return pb_1.Message.getWrapperField(this, dependency_8.Oreka.SubscribeTicker, 46) as dependency_8.Oreka.SubscribeTicker;
        }
        set subscribeticker(value: dependency_8.Oreka.SubscribeTicker) {
            pb_1.Message.setOneofWrapperField(this, 46, this.#one_of_decls[7], value);
        }
        get has_subscribeticker() {
            return pb_1.Message.getField(this, 46) != null;
        }
        get tickdata() {
            return pb_1.Message.getWrapperField(this, dependency_9.Oreka.TickData, 61) as dependency_9.Oreka.TickData;
        }
        set tickdata(value: dependency_9.Oreka.TickData) {
            pb_1.Message.setOneofWrapperField(this, 61, this.#one_of_decls[8], value);
        }
        get has_tickdata() {
            return pb_1.Message.getField(this, 61) != null;
        }
        get _loginrequest() {
            const cases: {
                [index: number]: "none" | "loginrequest";
            } = {
                0: "none",
                2: "loginrequest"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        get _loginresponse() {
            const cases: {
                [index: number]: "none" | "loginresponse";
            } = {
                0: "none",
                3: "loginresponse"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        get _fetchDealingdatainterval() {
            const cases: {
                [index: number]: "none" | "fetchDealingdatainterval";
            } = {
                0: "none",
                7: "fetchDealingdatainterval"
            };
            return cases[pb_1.Message.computeOneofCase(this, [7])];
        }
        get _loginbytoken() {
            const cases: {
                [index: number]: "none" | "loginbytoken";
            } = {
                0: "none",
                10: "loginbytoken"
            };
            return cases[pb_1.Message.computeOneofCase(this, [10])];
        }
        get _dealingdatainterval() {
            const cases: {
                [index: number]: "none" | "dealingdatainterval";
            } = {
                0: "none",
                20: "dealingdatainterval"
            };
            return cases[pb_1.Message.computeOneofCase(this, [20])];
        }
        get _fetchlogindevice() {
            const cases: {
                [index: number]: "none" | "fetchlogindevice";
            } = {
                0: "none",
                87: "fetchlogindevice"
            };
            return cases[pb_1.Message.computeOneofCase(this, [87])];
        }
        get _logindevicelog() {
            const cases: {
                [index: number]: "none" | "logindevicelog";
            } = {
                0: "none",
                88: "logindevicelog"
            };
            return cases[pb_1.Message.computeOneofCase(this, [88])];
        }
        get _subscribeticker() {
            const cases: {
                [index: number]: "none" | "subscribeticker";
            } = {
                0: "none",
                46: "subscribeticker"
            };
            return cases[pb_1.Message.computeOneofCase(this, [46])];
        }
        get _tickdata() {
            const cases: {
                [index: number]: "none" | "tickdata";
            } = {
                0: "none",
                61: "tickdata"
            };
            return cases[pb_1.Message.computeOneofCase(this, [61])];
        }
        static fromObject(data: {
            type?: string;
            loginrequest?: ReturnType<typeof dependency_1.Oreka.LoginRequest.prototype.toObject>;
            loginresponse?: ReturnType<typeof dependency_2.Oreka.LoginResponse.prototype.toObject>;
            fetchDealingdatainterval?: ReturnType<typeof dependency_5.Oreka.FetchDealingDataInterval.prototype.toObject>;
            loginbytoken?: ReturnType<typeof dependency_3.Oreka.LoginByToken.prototype.toObject>;
            dealingdatainterval?: ReturnType<typeof dependency_4.Oreka.DealingDataInterval.prototype.toObject>;
            fetchlogindevice?: ReturnType<typeof dependency_6.Oreka.FetchLoginDevice.prototype.toObject>;
            logindevicelog?: ReturnType<typeof dependency_7.Oreka.LoginDeviceLog.prototype.toObject>;
            subscribeticker?: ReturnType<typeof dependency_8.Oreka.SubscribeTicker.prototype.toObject>;
            tickdata?: ReturnType<typeof dependency_9.Oreka.TickData.prototype.toObject>;
        }): ClientMessage {
            const message = new ClientMessage({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.loginrequest != null) {
                message.loginrequest = dependency_1.Oreka.LoginRequest.fromObject(data.loginrequest);
            }
            if (data.loginresponse != null) {
                message.loginresponse = dependency_2.Oreka.LoginResponse.fromObject(data.loginresponse);
            }
            if (data.fetchDealingdatainterval != null) {
                message.fetchDealingdatainterval = dependency_5.Oreka.FetchDealingDataInterval.fromObject(data.fetchDealingdatainterval);
            }
            if (data.loginbytoken != null) {
                message.loginbytoken = dependency_3.Oreka.LoginByToken.fromObject(data.loginbytoken);
            }
            if (data.dealingdatainterval != null) {
                message.dealingdatainterval = dependency_4.Oreka.DealingDataInterval.fromObject(data.dealingdatainterval);
            }
            if (data.fetchlogindevice != null) {
                message.fetchlogindevice = dependency_6.Oreka.FetchLoginDevice.fromObject(data.fetchlogindevice);
            }
            if (data.logindevicelog != null) {
                message.logindevicelog = dependency_7.Oreka.LoginDeviceLog.fromObject(data.logindevicelog);
            }
            if (data.subscribeticker != null) {
                message.subscribeticker = dependency_8.Oreka.SubscribeTicker.fromObject(data.subscribeticker);
            }
            if (data.tickdata != null) {
                message.tickdata = dependency_9.Oreka.TickData.fromObject(data.tickdata);
            }
            return message;
        }
        toObject() {
            const data: {
                type?: string;
                loginrequest?: ReturnType<typeof dependency_1.Oreka.LoginRequest.prototype.toObject>;
                loginresponse?: ReturnType<typeof dependency_2.Oreka.LoginResponse.prototype.toObject>;
                fetchDealingdatainterval?: ReturnType<typeof dependency_5.Oreka.FetchDealingDataInterval.prototype.toObject>;
                loginbytoken?: ReturnType<typeof dependency_3.Oreka.LoginByToken.prototype.toObject>;
                dealingdatainterval?: ReturnType<typeof dependency_4.Oreka.DealingDataInterval.prototype.toObject>;
                fetchlogindevice?: ReturnType<typeof dependency_6.Oreka.FetchLoginDevice.prototype.toObject>;
                logindevicelog?: ReturnType<typeof dependency_7.Oreka.LoginDeviceLog.prototype.toObject>;
                subscribeticker?: ReturnType<typeof dependency_8.Oreka.SubscribeTicker.prototype.toObject>;
                tickdata?: ReturnType<typeof dependency_9.Oreka.TickData.prototype.toObject>;
            } = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.loginrequest != null) {
                data.loginrequest = this.loginrequest.toObject();
            }
            if (this.loginresponse != null) {
                data.loginresponse = this.loginresponse.toObject();
            }
            if (this.fetchDealingdatainterval != null) {
                data.fetchDealingdatainterval = this.fetchDealingdatainterval.toObject();
            }
            if (this.loginbytoken != null) {
                data.loginbytoken = this.loginbytoken.toObject();
            }
            if (this.dealingdatainterval != null) {
                data.dealingdatainterval = this.dealingdatainterval.toObject();
            }
            if (this.fetchlogindevice != null) {
                data.fetchlogindevice = this.fetchlogindevice.toObject();
            }
            if (this.logindevicelog != null) {
                data.logindevicelog = this.logindevicelog.toObject();
            }
            if (this.subscribeticker != null) {
                data.subscribeticker = this.subscribeticker.toObject();
            }
            if (this.tickdata != null) {
                data.tickdata = this.tickdata.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.type.length)
                writer.writeString(1, this.type);
            if (this.has_loginrequest)
                writer.writeMessage(2, this.loginrequest, () => this.loginrequest.serialize(writer));
            if (this.has_loginresponse)
                writer.writeMessage(3, this.loginresponse, () => this.loginresponse.serialize(writer));
            if (this.has_fetchDealingdatainterval)
                writer.writeMessage(7, this.fetchDealingdatainterval, () => this.fetchDealingdatainterval.serialize(writer));
            if (this.has_loginbytoken)
                writer.writeMessage(10, this.loginbytoken, () => this.loginbytoken.serialize(writer));
            if (this.has_dealingdatainterval)
                writer.writeMessage(20, this.dealingdatainterval, () => this.dealingdatainterval.serialize(writer));
            if (this.has_fetchlogindevice)
                writer.writeMessage(87, this.fetchlogindevice, () => this.fetchlogindevice.serialize(writer));
            if (this.has_logindevicelog)
                writer.writeMessage(88, this.logindevicelog, () => this.logindevicelog.serialize(writer));
            if (this.has_subscribeticker)
                writer.writeMessage(46, this.subscribeticker, () => this.subscribeticker.serialize(writer));
            if (this.has_tickdata)
                writer.writeMessage(61, this.tickdata, () => this.tickdata.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ClientMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ClientMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.loginrequest, () => message.loginrequest = dependency_1.Oreka.LoginRequest.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.loginresponse, () => message.loginresponse = dependency_2.Oreka.LoginResponse.deserialize(reader));
                        break;
                    case 7:
                        reader.readMessage(message.fetchDealingdatainterval, () => message.fetchDealingdatainterval = dependency_5.Oreka.FetchDealingDataInterval.deserialize(reader));
                        break;
                    case 10:
                        reader.readMessage(message.loginbytoken, () => message.loginbytoken = dependency_3.Oreka.LoginByToken.deserialize(reader));
                        break;
                    case 20:
                        reader.readMessage(message.dealingdatainterval, () => message.dealingdatainterval = dependency_4.Oreka.DealingDataInterval.deserialize(reader));
                        break;
                    case 87:
                        reader.readMessage(message.fetchlogindevice, () => message.fetchlogindevice = dependency_6.Oreka.FetchLoginDevice.deserialize(reader));
                        break;
                    case 88:
                        reader.readMessage(message.logindevicelog, () => message.logindevicelog = dependency_7.Oreka.LoginDeviceLog.deserialize(reader));
                        break;
                    case 46:
                        reader.readMessage(message.subscribeticker, () => message.subscribeticker = dependency_8.Oreka.SubscribeTicker.deserialize(reader));
                        break;
                    case 61:
                        reader.readMessage(message.tickdata, () => message.tickdata = dependency_9.Oreka.TickData.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ClientMessage {
            return ClientMessage.deserialize(bytes);
        }
    }
}
