/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: loginresponse.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./tabdata";
import * as pb_1 from "google-protobuf";
export namespace Oreka {
    export class LoginResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            type?: string;
            status?: string;
            logintoken?: string;
            data?: dependency_1.Oreka.TabData;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("logintoken" in data && data.logintoken != undefined) {
                    this.logintoken = data.logintoken;
                }
                if ("data" in data && data.data != undefined) {
                    this.data = data.data;
                }
            }
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get logintoken() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set logintoken(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get data() {
            return pb_1.Message.getWrapperField(this, dependency_1.Oreka.TabData, 4) as dependency_1.Oreka.TabData;
        }
        set data(value: dependency_1.Oreka.TabData) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        get has_data() {
            return pb_1.Message.getField(this, 4) != null;
        }
        static fromObject(data: {
            type?: string;
            status?: string;
            logintoken?: string;
            data?: ReturnType<typeof dependency_1.Oreka.TabData.prototype.toObject>;
        }): LoginResponse {
            const message = new LoginResponse({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.logintoken != null) {
                message.logintoken = data.logintoken;
            }
            if (data.data != null) {
                message.data = dependency_1.Oreka.TabData.fromObject(data.data);
            }
            return message;
        }
        toObject() {
            const data: {
                type?: string;
                status?: string;
                logintoken?: string;
                data?: ReturnType<typeof dependency_1.Oreka.TabData.prototype.toObject>;
            } = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.logintoken != null) {
                data.logintoken = this.logintoken;
            }
            if (this.data != null) {
                data.data = this.data.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.type.length)
                writer.writeString(1, this.type);
            if (this.status.length)
                writer.writeString(2, this.status);
            if (this.logintoken.length)
                writer.writeString(3, this.logintoken);
            if (this.has_data)
                writer.writeMessage(4, this.data, () => this.data.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LoginResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LoginResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readString();
                        break;
                    case 2:
                        message.status = reader.readString();
                        break;
                    case 3:
                        message.logintoken = reader.readString();
                        break;
                    case 4:
                        reader.readMessage(message.data, () => message.data = dependency_1.Oreka.TabData.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): LoginResponse {
            return LoginResponse.deserialize(bytes);
        }
    }
}
